const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$('#theme').addEventListener('click',e=>{const on=document.body.classList.toggle('darkmode');e.currentTarget.textContent=on?'☀ Light mode':'◐ Theme';e.currentTarget.setAttribute('aria-pressed',String(on))});
$$('.reveal').forEach(b=>b.addEventListener('click',()=>{const p=document.getElementById(b.dataset.target);p.hidden=!p.hidden;b.textContent=p.hidden?'Reveal an example ＋':'Hide example −'}));
$('#showAnswer').addEventListener('click',()=>{const p=$('#promptAnswer');p.hidden=!p.hidden;$('#showAnswer').textContent=p.hidden?'Show a possible answer':'Hide possible answer'});
const steps=[
{client:'Request sent',server:'Waiting',lane:'REQUEST →',msg:'The browser sends an HTTP request asking the web server for a page or resource.',dir:'right',node:'client'},
{client:'Request sent',server:'Request received',lane:'Processing…',msg:'The server receives the request and determines how to respond. The real process may involve application logic and data.',dir:'none',node:'webserver'},
{client:'Waiting for response',server:'Response sent',lane:'← RESPONSE',msg:'The server sends an HTTP response. It can include a status code and requested content, or an error response.',dir:'left',node:'webserver'},
{client:'Page displayed',server:'Response complete',lane:'Page loaded',msg:'The browser interprets the returned HTML and loads associated resources such as CSS, JavaScript, and images to display the page.',dir:'none',node:'client'}];let step=0;
function renderSim(){ $('#stepCounter').textContent=`Step ${step} of 4`;$('#clientStatus').textContent=step?steps[Math.min(step-1,3)].client:'Waiting';$('#serverStatus').textContent=step?steps[Math.min(step-1,3)].server:'Waiting';$('#client').classList.toggle('active',step===1||step===4);$('#webserver').classList.toggle('active',step===2||step===3);$('#nextStep').textContent=step===0?'Start request →':step<4?'Next step →':'Run again ↻';const p=$('#packet');p.className='';if(!step){$('#laneLabel').textContent='Ready to send a request';$('#simMessage').textContent='Ready? Press “Start request” to ask the server for a web page.'}else{const s=steps[step-1];$('#laneLabel').textContent=s.lane;$('#simMessage').textContent=s.msg;if(s.dir!=='none'){void p.offsetWidth;p.className=s.dir}}}
$('#nextStep').addEventListener('click',()=>{step=step>=4?0:step+1;renderSim()});$('#reset').addEventListener('click',()=>{step=0;renderSim()});
const urlParts={protocol:['Protocol / scheme','https:// indicates that the browser should communicate using HTTPS, which protects data in transit with encryption when correctly configured.'],subdomain:['Subdomain','learn is an optional subdivision of a domain. Organisations often use subdomains for learning platforms, services, or portals.'],domain:['Domain name','example is the domain-name portion shown in this teaching example. Domain names are easier to remember than numeric IP addresses.'],tld:['Top-level domain (TLD)','.edu is a top-level domain. Different TLDs have different registration policies; a TLD alone does not guarantee credibility.'],path:['Path','/topic1/web points to a resource or route on the site. The server or web application determines what content is returned.']};
$$('[data-part]').forEach(b=>b.addEventListener('click',()=>{$$('[data-part]').forEach(x=>x.classList.toggle('selected',x===b));const d=urlParts[b.dataset.part];$('#urlInfo').innerHTML=`<span>↗</span><div><small>URL COMPONENT</small><h3>${d[0]}</h3><p>${d[1]}</p></div>`}));
$('#contrast').addEventListener('click',e=>{const on=$('#demoPage').classList.toggle('contrast');e.currentTarget.setAttribute('aria-pressed',String(on));$('#demoCaption').textContent=on?'High contrast is on. Discuss how stronger contrast can improve readability for many users.':'Contrast restored. Compare the two versions.'});$('#textSize').addEventListener('click',e=>{const on=$('#demoPage').classList.toggle('bigtext');e.currentTarget.setAttribute('aria-pressed',String(on));$('#demoCaption').textContent=on?'Text is enlarged. Does the layout still work?':'Text size restored. Think about users who need to enlarge text.'});$('#demoAction').addEventListener('click',()=>$('#demoCaption').textContent='This is a demonstration button. On a real site, its label should match the action or destination.');
$$('.audit input').forEach(i=>i.addEventListener('change',()=>{$('#auditCount').textContent=`${$$('.audit input:checked').length} of 5 checked`;$('#auditFeedback').textContent=''}));$('#copyAudit').addEventListener('click',async()=>{const list=$$('.audit input:checked').map(i=>'- '+i.value);const text='CSF3133 Accessibility Audit\nChecks completed: '+list.length+'/5\n'+(list.length?list.join('\n'):'- No checklist items selected yet.');try{await navigator.clipboard.writeText(text);$('#auditFeedback').textContent='Group summary copied. Paste it into your notes.'}catch{$('#auditFeedback').textContent=text}});
const qs=[
{q:'Which statement best describes the relationship between the Internet and the Web?',a:['They are exactly the same thing.','The Web is one service that uses the Internet.','The Internet is a website inside the Web.'],c:1,w:'The Internet is the global network infrastructure; the Web is one service that operates over it.'},
{q:'In a typical web visit, what does the browser do first?',a:['Sends a request for a resource.','Stores the whole Internet.','Creates the server’s response.'],c:0,w:'The browser requests a resource. The server then processes the request and sends a response.'},
{q:'What is the main role of DNS?',a:['To style a page with colours.','To associate domain names with IP addresses and related DNS records.','To replace HTML.'],c:1,w:'DNS helps translate domain names into information used to locate Internet services.'},
{q:'Which protocol is primarily used to exchange web resources between browsers and web servers?',a:['SMTP','HTTP','IMAP'],c:1,w:'HTTP is used for web requests and responses; HTTPS is HTTP protected by TLS.'},
{q:'Which is a good accessibility practice?',a:['Use colour alone to communicate meaning.','Disable keyboard navigation.','Provide useful text alternatives for informative images.'],c:2,w:'Text alternatives help people who cannot see an image understand its relevant information.'}];let qi=0,choice=null,checked=false,score=0;
function renderQuiz(){if(qi>=qs.length){$('#quizCount').textContent='QUIZ COMPLETE';$('#progress').style.width='100%';$('#quizContent').innerHTML=`<h3 class="question">Nice work — you completed the quiz!</h3><p>You scored <b>${score} out of ${qs.length}</b>. ${score===qs.length?'Excellent understanding!':'Review the explanations, then try again to strengthen your understanding.'}</p>`;$('#quizFeedback').textContent='Discuss any answers that surprised you.';$('#quizNext').textContent='Complete';$('#quizNext').disabled=true;return}const q=qs[qi];choice=null;checked=false;$('#quizCount').textContent=`QUESTION ${qi+1} OF ${qs.length}`;$('#progress').style.width=`${(qi+1)/qs.length*100}%`;$('#quizContent').innerHTML=`<h3 class="question">${q.q}</h3><div class="answers">${q.a.map((a,i)=>`<label class="option"><input type="radio" name="answer" value="${i}"><span>${a}</span></label>`).join('')}</div>`;$('#quizFeedback').textContent='Choose one answer.';$('#quizNext').textContent='Check answer';$('#quizNext').disabled=true;$$('input[name="answer"]').forEach(i=>i.addEventListener('change',()=>{choice=+i.value;$('#quizNext').disabled=false}))}
$('#quizNext').addEventListener('click',()=>{if(qi>=qs.length)return;if(!checked){if(choice===null)return;const q=qs[qi];$$('.option').forEach((l,i)=>{const r=l.querySelector('input');r.disabled=true;if(i===q.c)l.classList.add('correct');if(i===choice&&i!==q.c)l.classList.add('incorrect')});const ok=choice===q.c;if(ok)score++;checked=true;$('#quizFeedback').textContent=(ok?'Correct! ':'Not quite. ')+q.w;$('#quizNext').textContent=qi===qs.length-1?'See results':'Next question'}else{qi++;renderQuiz()}});$('#quizReset').addEventListener('click',()=>{qi=0;score=0;choice=null;checked=false;renderQuiz()});renderQuiz();
async function copyText(text,feedback){try{await navigator.clipboard.writeText(text);feedback.textContent='Copied. You can now paste it into your notes.'}catch{feedback.textContent=text}}
$('#copyReflection').addEventListener('click',()=>{const text=$('#exitTicket').value.trim();if(!text){$('#reflectionFeedback').textContent='Write one reflection first, then copy it.';return}copyText(text,$('#reflectionFeedback'))});
